services:
  postgres:
    container_name: itgardendb-postgres
    image: postgres
    command:
      - "postgres"
      - "-c"
      - config_file=/etc/postgresql/postgresql.conf
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      PGDATA: "/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - ./init_db_scripts:/docker-entrypoint-initdb.d
      - ./data:/data
      - ./postgresql_custom.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4G
    networks:
      - net

  pgadmin:
    container_name: itgardendb-pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL?Variable not set}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD?Variable not set}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE?False}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
    networks:
      - net
  
  cloudbeaver:
    container_name: itgardendb-cloudbeaver
    image: dbeaver/cloudbeaver
    env_file:
      - .env
    volumes:
      - dbeaver-data:/var/lib/pgadmin
    ports:
      - "8978:8978"
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
    networks:
      - net
  
  postgres_exporter:
    container_name: itgardendb-exporter
    image: prometheuscommunity/postgres-exporter:v0.10.1
    env_file:
      - .env
    environment:
      DATA_SOURCE_URI: "postgres:5432/${POSTGRES_USER?Variable not set}?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER?Variable not set}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD?Variable not set}
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 500M
    networks:
      - net

volumes:
  itgarden-data:
  pgadmin-data:
  dbeaver-data:

networks:
  net:
    driver: bridge
